name: Check Spelling
on:
  workflow_dispatch:
  push:
    branches: 
        - 'main'
jobs:
  DiffCheck:
    name: Check Diff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["latest"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Make Diff
      uses: technote-space/get-diff-action@v6
      with:
        PATTERNS: |
          +(src|tests|E2E)/**/*.+(md|vue|js|html|json)
      #     !src/exclude.ts
      #     FILES: |
      #           yarn.lock
      #           .eslintrc
    - name: Print Changes
      run: echo '${{ env.GIT_DIFF }}' 
    - name: Get Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run CSpell
      run: npx cspell --no-progress --show-context --no-exit-code ${{ env.GIT_DIFF }}